### ISSUE TITLE
Potential problems with mega-farmout and login machines

### ISSUE THREAD

**Issue by dntaylor** [uwcms/FinalStateAnalysis#536]
Hello all,

The login machines have been periodically unresponsive the past few days.
While we had some fun blaming Kenneth, I suspect the issue is actually arising from the mega-farmout script.

I personally don't know how this script works. Does it read/write a lot to afs? If so, can it be modified to read/write to hdfs instead? Getting to a state where the `--shared-fs` option can be deleted should reduce the load.

@Nabarun21 @fanbomeng I notice you have had a bunch of these scripts running for the past few days. Any insights?

Thanks,
Devin

**Comment by fanbomeng** [comment]
Hi Devin,

Yes, the login machines has some problems. the jobs I am running are from HDFS space. But indeed, I run a lot of mega jobs these days, for now I am not sure if this is the cause, if so, the way to fix it. if further any suggestions, please inform me.

Best

Fanbo
On Oct 7, 2016, at 10:59 AM, Devin Taylor <notifications@github.com<mailto:notifications@github.com>> wrote:

Hello all,

The login machines have been periodically unresponsive the past few days.
While we had some fun blaming Kenneth, I suspect the issue is actually arising from the mega-farmout script.

I personally don't know how this script works. Does it read/write a lot to afs? If so, can it be modified to read/write to hdfs instead? Getting to a state where the --shared-fs option can be deleted should reduce the load.

@Nabarun21https://github.com/Nabarun21 @fanbomenghttps://github.com/fanbomeng I notice you have had a bunch of these scripts running for the past few days. Any insights?

Thanks,
Devin

**Comment by dntaylor** [comment]
Hi Fanbo,

Can you try deleting this line: https://github.com/uwcms/FinalStateAnalysis/blob/miniAOD_8_0_13/PlotTools/scripts/mega-farmout#L125, recompiling, and submitting a test job to see if your script still runs correctly?

If so, we should remove it since this tells farmoutAnalysisJobs to not tar up the work area and so actually reads directly from afs rather than the usercode copied to the node.

Devin

**Comment by fanbomeng** [comment]
Hi Devin,

I have been tasting the jobs running without --shared-fs, so far they have been running for 2 hours, not finished yet, I will update you when I have firm results

Best

Fanbo
On Oct 7, 2016, at 11:13 AM, Devin Taylor <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Fanbo,

Can you try deleting this line: https://github.com/uwcms/FinalStateAnalysis/blob/miniAOD_8_0_13/PlotTools/scripts/mega-farmout#L125, recompiling, and submitting a test job to see if your script still runs correctly?

If so, we should remove it since this tells farmoutAnalysisJobs to not tar up the work area and so actually reads directly from afs rather than the usercode copied to the node.

Devin

**Comment by dntaylor** [comment]
Looks like there was a network issue connecting US and CERN. Let's hope that was the cause of the freezing.

**Comment by fanbomeng** [comment]
ok, hopefully we can solve the problem soon.  we have kill all of the mega jobs that can be shown with  ps aux , and also do not submit new jobs with condor, if still not covered, then it is not the problem with condor itself.

Best

Fanbo
On Oct 7, 2016, at 5:22 PM, Devin Taylor <notifications@github.com<mailto:notifications@github.com>> wrote:

Looks like there was a network issue connecting US and CERN. Let's hope that was the cause of the freezing.

**Comment by dntaylor** [comment]
I'm closing this. Seems like it was definitely related to the network instability. Though I do encourage removing the shared-fs option.

Devin
